controller_list:
  - name: fake_kinova_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
  - name: fake_Fingertip1_controller
    type: $(arg fake_execution_type)
    joints:
      - 3
  - name: fake_Fingertip2_controller
    type: $(arg fake_execution_type)
    joints:
      - 7
  - name: fake_Fingertip3_controller
    type: $(arg fake_execution_type)
    joints:
      - 11
  - name: fake_ThumbFingertip_controller
    type: $(arg fake_execution_type)
    joints:
      - 15
  - name: fake_Palm_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_Finger1_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
      - 1
      - 0
      - 2
      - 3
  - name: fake_Finger2_controller
    type: $(arg fake_execution_type)
    joints:
      - 5
      - 4
      - 6
      - 7
  - name: fake_Finger3_controller
    type: $(arg fake_execution_type)
    joints:
      - 9
      - 8
      - 10
      - 11
  - name: fake_ThumbFinger_controller
    type: $(arg fake_execution_type)
    joints:
      - 12
      - 13
      - 14
      - 15
initial:  # Define initial robot poses per group
  - group: kinova_arm
    pose: home